export const services = [
    {
        title: "Data Strategy and Solutions",
        icon: "📊",
        description: "Empower your organization with structured, scalable, and insightful data operations.",
        items: [
            "Automated Data Collection & Web Scraping",
            "Data Integration & Pipeline Development",
            "Data Warehousing & Data Lakes",
            "Data Engineering & Architecture Design",
            "Business Intelligence & Data Visualization",
            "Reporting & Dashboard Solutions",
            "Data Analytics & Insight Generation",
        ],
    },
    {
        title: "AI Transformation",
        icon: "🤖",
        description: "Harness artificial intelligence to drive innovation and smarter decision-making.",
        items: [
            "Custom AI/ML Model Development",
            "Natural Language Processing (NLP)",
            "Computer Vision & Image Processing",
            "Predictive Analytics & Forecasting Models",
            "Recommendation Engine Development",
            "AI-Powered Chatbots & Virtual Assistants",
            "Cognitive Process Automation (Cognitive RPA)",
            "Model Deployment, Monitoring & MLOps",
            "Custom LLM (Large Language Model) Integration",
        ],
    },
    {
        title: "Automation",
        icon: "⚙️",
        description: "Streamline and optimize processes across your digital landscape.",
        items: [
            "Web Data Scraping & Task Automation",
            "End-to-End Business Process Automation",
            "Robotic Process Automation (RPA)",
            "Chatbot Deployment & Workflow Integration",
            "ERP/CRM Process Automation",
            "Workflow Automation (Zapier, Power Automate)",
            "Infrastructure Automation (CI/CD, Terraform, Ansible)",
        ],
    },
];
